workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - release

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: ./ci/release.sh